spring:
  profiles:
    active: dev
  application:
    name: mySingerbackend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi2?serverTimezone=Asia/Shanghai
    username: root
    #password: Lyc123456
    password: 123456
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 2
    #password: Lyc123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
  address: 0.0.0.0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/**/*Mapper.xml

aliyun:
  oss:
    file:
      endpoint: xxxx
      keyid: xxxxx
      keysecret: xxxx
      bucketname: xxxx
    config:
      oss-switch: x
      oss-directory: xxxx
